# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AZExpress' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'SVProgressHUD'
pod 'IQKeyboardManagerSwift'
pod 'CameraManager'
pod 'JKCalendar'
pod 'Firebase'
pod 'FirebaseDatabase'
#pod 'AlamofireObjectMapper' #, '~> 5.2.1'
#pod 'AlamofireImage'
  # Pods for AZExpress

end
